// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXk95W8iw5bNsRYdBkS5_jRLjiJ5FZcFk',
    appId: '1:417886583896:web:c0ee4400034b8502a01e2d',
    messagingSenderId: '417886583896',
    projectId: 'reveal-her-potential',
    authDomain: 'reveal-her-potential.firebaseapp.com',
    storageBucket: 'reveal-her-potential.appspot.com',
    measurementId: 'G-LBEPDTCKBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjcVc3wR6CCTe9VV40n6OZKzi65DLAgk',
    appId: '1:417886583896:android:dcb42a4fc9aa1449a01e2d',
    messagingSenderId: '417886583896',
    projectId: 'reveal-her-potential',
    storageBucket: 'reveal-her-potential.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKxZ8j67aotN3MoafTmhry0vPdClWUsrM',
    appId: '1:417886583896:ios:3780ad21fe79415da01e2d',
    messagingSenderId: '417886583896',
    projectId: 'reveal-her-potential',
    storageBucket: 'reveal-her-potential.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRhp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKxZ8j67aotN3MoafTmhry0vPdClWUsrM',
    appId: '1:417886583896:ios:e353e8b1563f6846a01e2d',
    messagingSenderId: '417886583896',
    projectId: 'reveal-her-potential',
    storageBucket: 'reveal-her-potential.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRhp.RunnerTests',
  );
}

